### PR TITLE
updating install in readme

### PR DESCRIPTION
**Pull request by jmervine**
cc @jdorfman

### CODE REVIEW

**Comment by jdorfman** [comment]
There is a typo `s/Max/Mac/g`

Maybe even replace "Mac" with "Darwin" since the SHML audience must know that Darwin === OS X

**Comment by jmervine** [comment]
Good catch. I'll hit that shortly.

**Comment by jmervine** [comment]
@jdorfman If you don't have any more comments, feel free to merge this.

**Comment by jmervine** [comment]
@jdorfman once this is merged, you should up the the gh-pages as well...

**Comment by jdorfman** [comment]
looks good.  I will update the docs after this.

**Pull request merged**
